openapi: 3.1.0
info:
  title: Kona API Specification
  description: |-
    Kona is an image processing server written in TypeScript. It has API that you can use to upload, change, delete, or do stuff that Kona server supports.
    
    If server enabled config `API_AUTH_ENABLED`, all request MUST have a valid `Authorization` headers in the form of Bearer token (not in format of JWT).
  license:
    name: MIT License
    url: https://github.com/BadAimWeeb/kona/blob/main/LICENSE
  version: 0.0.1
servers:
  - url: https
tags:
  - name: master
    description: Endpoint only master API key can use, authenticate with value configured at `MASTER_API_KEY` in the server.
paths:
  /api/app-api-key:
    post:
      tags:
        - master
      summary: Create a new API key
      description: Create a new API key that can be safely used in other applications/servers.
      operationId: createAppAPIKey
      responses:
        '200':
          description: Successful operation, will return a new API key that can be safely used in other applications/servers.
          content:
            application/json:
              schema:
                type: object
                properties:
                  key:
                    type: string
                    description: New API key
                  uuid:
                    type: string
                    format: uuid
                    description: ID of the new API key
                examples:
                  - key: kona_sk_MDEyMzAxMjMwMTIzMDEyMzAxMjMwMTIzMDEyMzAxMjM
                    uuid: 144bb86e-be58-411c-be94-35ca1df5515e
        '401':
          description: Invalid Authorization header
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  securitySchemes:
    api_key:
      type: http
      scheme: Bearer
  schemas:
    error:
      type: object
      properties:
        error:
          type: string
          description: Error message
        error_code:
          type: integer
          description: Error code
        kona_version:
          type: string
          description: Kona version this server is running
      examples:
        - error: Some error message
          error_code: 1
          kona_version: 0.0.1
security: 
- api_key: []